/**
 * Vitest global setup: purge the gitignored scratch root before any test file runs.
 *
 * Everything under `test/tmp/` is generated by the suite (see `test/list-sessions-filters.test.ts`
 * and `test/session-metadata.test.ts`), so a run must never read state an earlier run left behind.
 * This hook runs once, in the main process, before the workers collect any test file, which makes
 * the fresh-tmp guarantee identical for `npm test`, `npm run coverage`, `npm run check`, a single
 * `vitest run <file>`, and CI — an npm-script `clean` step alone would only cover the last one.
 *
 * No teardown: the artifacts stay on disk after a run so a failure can be inspected, and the next
 * run's purge makes staleness impossible. Committed fixtures under `test/fixtures/` are untouched.
 */

import { rm } from "node:fs/promises";

export default async function setup(): Promise<void> {
  await rm(new URL("tmp/", import.meta.url).pathname, { recursive: true, force: true });
}
